CUDA_VISIBLE_DEVICES=4,5,6,7 python generate.py \
  --prompt-type lmd_attribution \
  --model gpt-4 \
  --save-suffix "gpt-4" \
  --repeats 1 \
  --frozen_step_ratio 0.5 \
  --regenerate 1 \
  --force_run_ind 0 \
  --run-model lmd_plus \
  --no-scale-boxes-default \
  --template_version v0.2 \
  --experiment True